// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechCareerMVCFinal.Data;

#nullable disable

namespace TechCareerMVCFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechCareerMVCFinal.Models.Kiyafet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fiyati")
                        .HasColumnType("float");

                    b.Property<string>("KiyafetAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KiyafetTuruId")
                        .HasColumnType("int");

                    b.Property<string>("Rengi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KiyafetTuruId");

                    b.ToTable("Kiyafetler");
                });

            modelBuilder.Entity("TechCareerMVCFinal.Models.KiyafetTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("KiyafetTurleri");
                });

            modelBuilder.Entity("TechCareerMVCFinal.Models.SiparisVerme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KiyafetId")
                        .HasColumnType("int");

                    b.Property<int>("kullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KiyafetId");

                    b.ToTable("SiparisVerme");
                });

            modelBuilder.Entity("TechCareerMVCFinal.Models.Kiyafet", b =>
                {
                    b.HasOne("TechCareerMVCFinal.Models.KiyafetTuru", "KiyafetTuru")
                        .WithMany()
                        .HasForeignKey("KiyafetTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KiyafetTuru");
                });

            modelBuilder.Entity("TechCareerMVCFinal.Models.SiparisVerme", b =>
                {
                    b.HasOne("TechCareerMVCFinal.Models.Kiyafet", "Kiyafet")
                        .WithMany()
                        .HasForeignKey("KiyafetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiyafet");
                });
#pragma warning restore 612, 618
        }
    }
}
